"""This modules contains the basic Generator classes."""

from __future__ import annotations

from abc import ABC
from abc import abstractmethod
from dataclasses import dataclass

# from typing import Self
from typing import Generic
from typing import TypeVar
from typing import Union

from typing_extensions import Self

from .utils import zip_strict


# region TypeVars used by generics

T = TypeVar("T", bool, str, float, int)
U = TypeVar("U", bool, str, float, int)
T_SFI = TypeVar("T_SFI", str, float, int)
T_BFI = TypeVar("T_BFI", bool, float, int)
T_FI = TypeVar("T_FI", float, int)
T_BI = TypeVar("T_BI", bool, int)
T_BF = TypeVar("T_BF", bool, float)
T_F = TypeVar("T_F", float, float)
T_B = TypeVar("T_B", bool, bool)
T_I = TypeVar("T_I", int, int)

Numeric = Union[int, float]

# endregion

# region Generic Abstract Classes


@dataclass
class Generator(Generic[T], ABC):
    """Basic Abstract Generator Class."""

    @abstractmethod
    def generate(self, n: int) -> list[T]:
        """Generate n values.

        Args:
            n (int): The number of values to generate.

        Returns:
            list[T]: The generated values.
        """
        ...

    @abstractmethod
    def copy(self) -> Self:
        """Create a copy of the Generator.

        Returns:
            Self: The copied Generator.
        """
        ...

    def to_int(self) -> GeneratorInt:
        """Convert the Generator to a Generator of integers.

        Returns:
            GeneratorInt: The converted Generator.
        """
        return GeneratorWrapperInt(self)

    def to_float(self) -> GeneratorFloat:
        """Convert the Generator to a Generator of floats.

        Returns:
            GeneratorFloat: The converted Generator.
        """
        return GeneratorWrapperFloat(self)

    def to_str(self) -> GeneratorStr:
        """Convert the Generator to a Generator of strings.

        Returns:
            GeneratorStr: The converted Generator.
        """
        return GeneratorWrapperStr(self)

    def to_bool(self) -> GeneratorBool:
        """Convert the Generator to a Generator of booleans.

        Returns:
            GeneratorBool: The converted Generator.
        """
        return GeneratorWrapperBool(self)


@dataclass
class GeneratorComposite(Generator[T], ABC):
    """A Composite Generator that combines two Generators.

    Args:
        left (Generator[T]): The left Generator.
        right (Generator[T]): The right Generator.
    """

    left: Generator[T]
    right: Generator[T]

    @abstractmethod
    def generate(self, n: int) -> list[T]:
        """Generate n values.

        Args:
            n (int): The number of values to generate.

        Returns:
            list[str]: The generated values.
        """
        ...

    def zip_generators(self, n: int) -> zip[tuple[T, T]]:
        """Perform 'Zip the values generated by' on XXX Generators (or constant).

        Args:
            n (int): The number of values to generate.

        Returns:
            zip[tuple[T, T]]: The zipped values.
        """
        lhs_values: list[T] = self.left.generate(n)
        rhs_values: list[T] = self.right.generate(n)
        return zip_strict(lhs_values, rhs_values)

    def copy(self) -> Self:
        """Create a copy of the GeneratorComposite.

        Returns:
            Self: The copied GeneratorComposite.
        """
        return self.__class__(self.left.copy(), self.right.copy())


@dataclass
class GeneratorWrapper(Generator[T], Generic[U, T], ABC):
    """A Wrapper class for converting Generators.

    Args:
        internal (Generator[U]): The internal Generator.
    """

    internal: Generator[U]

    def copy(self) -> Self:
        """Create a copy of the GeneratorWrapper.

        Returns:
            Self: The copied GeneratorWrapper.
        """
        return self.__class__(self.internal.copy())

    @staticmethod
    def convert(x: U, t: type[T]) -> T:
        """Convert the internal value to the response type.

        Args:
            x (U): The value to convert.
            t (type[T]): The type to convert to.

        Returns:
            T: The converted value.
        """
        try:
            return t(x)
        except ValueError:
            return t()

    def wrapper_generate(self, n: int, t: type[T]) -> list[T]:
        """Generate n values by converting the generated values to floats.

        Args:
            n (int):The number of values to generate.
            t (type[T]): The type to convert to.

        Returns:
            list[T]: The generated values.
        """
        return [GeneratorWrapper.convert(x, t) for x in self.internal.generate(n)]


@dataclass
class GeneratorConstant(Generator[T]):
    """A Generator that generates a constant value.

    Args:
        value (T): The constant value to generate.
    """

    value: T

    def generate(self, n: int) -> list[T]:
        """Generate n values.

        Args:
            n (int): The number of values to generate.

        Returns:
            list[T]: The generated values.
        """
        return [self.value for _ in range(n)]

    def copy(self) -> Self:
        """Create a copy of the Generator.

        Returns:
            Self: The copied Generator.
        """
        return self.__class__(self.value)


# endregion

# region Abstract Typed Base Classes


@dataclass
class GeneratorBool(Generator[bool], ABC):
    """Abstract Base Class for Generators that generate booleans."""

    def to_bool(self) -> GeneratorBool:
        """Convert the Generator to a Generator of booleans.

        Returns:
            GeneratorBool: The converted Generator.
        """
        return self.copy()

    @staticmethod
    def coerce(x: GeneratorBool | bool) -> GeneratorBool:
        """Coerce a boolean to a GeneratorBool.

        Args:
            x (GeneratorBool|bool): The value to coerce.

        Returns:
            GeneratorBool: The coerced value.
        """
        if isinstance(x, bool):
            return ConstantBool(x)
        return x

    def __and__(self, other: GeneratorBool | bool) -> GeneratorCompositeAndBool:
        """Perform 'And' on boolean Generators (or constant).

        Args:
            other (GeneratorBool | bool): The other boolean Generator.

        Returns:
            GeneratorCompositeAndBool: The Composite Generator.
        """
        other = GeneratorBool.coerce(other)
        return GeneratorCompositeAndBool(self, other)

    def __or__(self, other: GeneratorBool | bool) -> GeneratorCompositeOrBool:
        """Perform 'Or' on boolean Generators (or constant).

        Args:
            other (GeneratorBool | bool): The other boolean Generator.

        Returns:
            GeneratorCompositeOrBool: The Composite Generator.
        """
        other = GeneratorBool.coerce(other)
        return GeneratorCompositeOrBool(self, other)

    def __xor__(self, other: GeneratorBool | bool) -> GeneratorCompositeXorBool:
        """Perform 'Xor' on boolean Generators (or constant).

        Args:
            other (GeneratorBool | bool): The other boolean Generator.

        Returns:
            GeneratorCompositeXorBool: The Composite Generator.
        """
        other = GeneratorBool.coerce(other)
        return GeneratorCompositeXorBool(self, other)


@dataclass
class GeneratorStr(Generator[str], ABC):
    """Abstract Base Class for Generators that generate strings."""

    def to_str(self) -> GeneratorStr:
        """Convert the Generator to a Generator of strings.

        Returns:
            GeneratorStr: The converted Generator.
        """
        return self.copy()

    @staticmethod
    def coerce(x: GeneratorStr | str) -> GeneratorStr:
        """Coerce a string to a GeneratorStr.

        Args:
            x (GeneratorStr|str): The value to coerce.

        Returns:
            GeneratorStr: The coerced value.
        """
        if isinstance(x, str):
            return ConstantStr(x)
        return x

    def __add__(self, other: GeneratorStr) -> GeneratorCompositeAddStr:
        """Perform 'Add' on string Generators (or constant).

        Args:
            other (GeneratorStr): The other string Generator.

        Returns:
            GeneratorCompositeAddStr: The Composite Generator.
        """
        other = GeneratorStr.coerce(other)
        return GeneratorCompositeAddStr(self, other)


@dataclass
class GeneratorFloat(Generator[float], ABC):
    """Abstract Base Class for Generators that generate floats."""

    def to_float(self) -> GeneratorFloat:
        """Convert the Generator to a Generator of floats.

        Returns:
            GeneratorFloat: The converted Generator.
        """
        return self.copy()

    @staticmethod
    def coerce(x: GeneratorNumeric | Numeric) -> GeneratorFloat:
        """Coerce a numeric to a GeneratorFloat.

        Args:
            x (GeneratorNumeric|Numeric): The value to coerce.

        Returns:
            GeneratorFloat: The coerced value.
        """
        if isinstance(x, int):
            return ConstantFloat(float(x))
        if isinstance(x, float):
            return ConstantFloat(x)
        if isinstance(x, GeneratorInt):
            return x.to_float()
        return x

    def __add__(self, other: GeneratorNumeric | Numeric) -> GeneratorCompositeAddFloat:
        """Perform 'Add' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeAddFloat: The Composite Generator.
        """
        other = GeneratorFloat.coerce(other)
        return GeneratorCompositeAddFloat(self, other)

    def __sub__(self, other: GeneratorNumeric | Numeric) -> GeneratorCompositeSubFloat:
        """Perform 'Subtract' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeSubFloat: The Composite Generator.
        """
        other = GeneratorFloat.coerce(other)
        return GeneratorCompositeSubFloat(self, other)

    def __mul__(self, other: GeneratorNumeric | Numeric) -> GeneratorCompositeMultFloat:
        """Perform 'Multiply' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeMultFloat: The Composite Generator.
        """
        other = GeneratorFloat.coerce(other)
        return GeneratorCompositeMultFloat(self, other)

    def __truediv__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositeTrueDivFloat:
        """Perform 'Divide' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeTrueDivFloat: The Composite Generator.
        """
        other = GeneratorFloat.coerce(other)
        return GeneratorCompositeTrueDivFloat(self, other)

    def __floordiv__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositeFloorDivFloat:
        """Perform 'Floor divide' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeFloorDivFloat: The Composite Generator.
        """
        other = GeneratorFloat.coerce(other)
        return GeneratorCompositeFloorDivFloat(self, other)

    def __pow__(self, other: GeneratorNumeric | Numeric) -> GeneratorCompositePowFloat:
        """Perform 'Exponentiate' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositePowFloat: The Composite Generator.
        """
        other = GeneratorFloat.coerce(other)
        return GeneratorCompositePowFloat(self, other)


@dataclass
class GeneratorInt(Generator[int], ABC):
    """Abstract Base Class for Generators that generate integers."""

    def to_int(self) -> GeneratorInt:
        """Convert the Generator to a Generator of integers.

        Returns:
            GeneratorInt: The converted Generator.
        """
        return self.copy()

    @staticmethod
    def coerce(x: GeneratorNumeric | Numeric) -> GeneratorNumeric:
        """Coerce a numeric to a GeneratorFloat.

        Args:
            x (GeneratorNumeric|Numeric): The value to coerce.

        Returns:
            GeneratorNumeric: The coerced value.
        """
        if isinstance(x, int):
            return ConstantInt(x)
        if isinstance(x, float):
            return ConstantFloat(x)
        return x

    def __add__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositeAddNumeric:
        """Perform 'Add' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeAddNumeric: The Composite Generator.
        """
        other = GeneratorInt.coerce(other)
        if isinstance(other, GeneratorFloat):
            return GeneratorCompositeAddFloat(self.to_float(), other)
        return GeneratorCompositeAddInt(self, other)

    def __sub__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositeSubNumeric:
        """Perform 'Subtract' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeSubNumeric: The Composite Generator.
        """
        other = GeneratorInt.coerce(other)
        if isinstance(other, GeneratorFloat):
            return GeneratorCompositeSubFloat(self.to_float(), other)
        return GeneratorCompositeSubInt(self, other)

    def __mul__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositeMultNumeric:
        """Perform 'Multiply' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeMultNumeric: The Composite Generator.
        """
        other = GeneratorInt.coerce(other)
        if isinstance(other, GeneratorFloat):
            return GeneratorCompositeMultFloat(self.to_float(), other)
        return GeneratorCompositeMultInt(self, other)

    def __floordiv__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositeFloorDivNumeric:
        """Perform 'Floor divide' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositeFloorDivNumeric: The Composite Generator.
        """
        other = GeneratorInt.coerce(other)
        if isinstance(other, GeneratorFloat):
            return GeneratorCompositeFloorDivFloat(self.to_float(), other)
        return GeneratorCompositeFloorDivInt(self, other)

    def __pow__(
        self, other: GeneratorNumeric | Numeric
    ) -> GeneratorCompositePowNumeric:
        """Perform 'Exponentiate' on numeric Generators (or constant).

        Args:
            other (GeneratorNumeric | Numeric): The other numeric Generator.

        Returns:
            GeneratorCompositePowNumeric: The Composite Generator.
        """
        other = GeneratorInt.coerce(other)
        if isinstance(other, GeneratorFloat):
            return GeneratorCompositePowFloat(self.to_float(), other)
        return GeneratorCompositePowInt(self, other)


GeneratorNumeric = Union[GeneratorInt, GeneratorFloat]

# endregion

# region Wrapper Classes


@dataclass
class GeneratorWrapperStr(GeneratorStr, GeneratorWrapper[U, str]):
    """A Wrapper class for converting Generators to string Generators."""

    def generate(self, n: int) -> list[str]:
        """Generate n values by converting the generated values to strings.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[str]: The generated values.
        """
        return self.wrapper_generate(n, str)


@dataclass
class GeneratorWrapperFloat(GeneratorFloat, GeneratorWrapper[U, float]):
    """A Wrapper class for converting Generators to float Generators."""

    def generate(self, n: int) -> list[float]:
        """Generate n values by converting the generated values to floats.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[float]: The generated values.
        """
        return self.wrapper_generate(n, float)


@dataclass
class GeneratorWrapperInt(GeneratorInt, GeneratorWrapper[U, int]):
    """A Wrapper class for converting Generators to integer Generators."""

    def generate(self, n: int) -> list[int]:
        """Generate n values by converting the generated values to integers.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[int]: The generated values.
        """
        return self.wrapper_generate(n, int)


@dataclass
class GeneratorWrapperBool(GeneratorBool, GeneratorWrapper[U, bool]):
    """A Wrapper class for converting Generators to boolean Generators."""

    def generate(self, n: int) -> list[bool]:
        """Generate n values by converting the generated values to booleans.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[bool]: The generated values.
        """
        return self.wrapper_generate(n, bool)


# endregion

# region Abstract Typed Composite Classes


@dataclass
class GeneratorCompositeAdd(GeneratorComposite[T_SFI]):
    """A Composite Generator that adds two Generators."""

    def generate(self, n: int) -> list[T_SFI]:
        """Generate n values by adding the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_SFI]: The generated values.
        """
        return [a + b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeSub(GeneratorComposite[T_FI]):
    """A Composite Generator that subtracts two Generators."""

    def generate(self, n: int) -> list[T_FI]:
        """Generate n values by subtracting the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_FI]: The generated values.
        """
        return [a - b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeMult(GeneratorComposite[T_FI]):
    """A Composite Generator that multiplies two Generators."""

    def generate(self, n: int) -> list[T_FI]:
        """Generate n values by multiplying the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_FI]: The generated values.
        """
        return [a * b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeTrueDiv(GeneratorComposite[T_F]):
    """A Composite Generator that divides two Generators."""

    def generate(self, n: int) -> list[T_F]:
        """Generate n values by dividing the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_F]: The generated values.
        """
        return [a / b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeFloorDiv(GeneratorComposite[T_FI]):
    """A Composite Generator that floor divides two Generators."""

    def generate(self, n: int) -> list[T_FI]:
        """Generate n values by floor dividing the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_FI]: The generated values.
        """
        return [a // b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositePow(GeneratorComposite[T_FI]):
    """A Composite Generator that exponentiates two Generators."""

    def generate(self, n: int) -> list[T_FI]:
        """Generate n values by exponentiating the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_FI]: The generated values.
        """
        return [a**b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeAnd(GeneratorComposite[T_B]):
    """A Composite Generator that ands two Generators."""

    def generate(self, n: int) -> list[T_B]:
        """Generate n values by anding the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_B]: The generated values.
        """
        return [a and b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeOr(GeneratorComposite[T_B]):
    """A Composite Generator that ors two Generators."""

    def generate(self, n: int) -> list[T_B]:
        """Generate n values by oring the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_B]: The generated values.
        """
        return [a or b for a, b in self.zip_generators(n)]


@dataclass
class GeneratorCompositeXor(GeneratorComposite[T_B]):
    """A Composite Generator that xors two Generators."""

    def generate(self, n: int) -> list[T_B]:
        """Generate n values by xoring the two generated values.

        Args:
            n (int):The number of values to generate.

        Returns:
            list[T_B]: The generated values.
        """
        return [a ^ b for a, b in self.zip_generators(n)]


# endregion

# region Composite Classes

# region Composite Classes for Addition


@dataclass
class GeneratorCompositeAddStr(GeneratorStr, GeneratorCompositeAdd[str]):
    """A Composite Generator that adds two String Generators."""


@dataclass
class GeneratorCompositeAddFloat(GeneratorFloat, GeneratorCompositeAdd[float]):
    """A Composite Generator that adds two Float Generators."""


@dataclass
class GeneratorCompositeAddInt(GeneratorInt, GeneratorCompositeAdd[int]):
    """A Composite Generator that adds two Integer Generators."""


# endregion
# region Composite Classes for Subtraction


@dataclass
class GeneratorCompositeSubFloat(GeneratorFloat, GeneratorCompositeSub[float]):
    """A Composite Generator that subtracts two Float Generators."""


@dataclass
class GeneratorCompositeSubInt(GeneratorInt, GeneratorCompositeSub[int]):
    """A Composite Generator that subtracts two Integer Generators."""


# endregion
# region Composite Classes for Multiplication


@dataclass
class GeneratorCompositeMultFloat(GeneratorFloat, GeneratorCompositeMult[float]):
    """A Composite Generator that multiplies two Float Generators."""


@dataclass
class GeneratorCompositeMultInt(GeneratorInt, GeneratorCompositeMult[int]):
    """A Composite Generator that multiplies two Integer Generators."""


# endregion
# region Composite Classes for True Division


@dataclass
class GeneratorCompositeTrueDivFloat(GeneratorFloat, GeneratorCompositeTrueDiv[float]):
    """A Composite Generator that divides two Float Generators."""


# endregion
# region Composite Classes for Floor Division


@dataclass
class GeneratorCompositeFloorDivFloat(
    GeneratorCompositeFloorDiv[float], GeneratorFloat
):
    """A Composite Generator that floor divides two Float Generators."""


@dataclass
class GeneratorCompositeFloorDivInt(GeneratorInt, GeneratorCompositeFloorDiv[int]):
    """A Composite Generator that floor divides two Integer Generators."""


# endregion
# region Composite Classes for Power


@dataclass
class GeneratorCompositePowFloat(GeneratorFloat, GeneratorCompositePow[float]):
    """A Composite Generator that exponentiates two Float Generators."""


@dataclass
class GeneratorCompositePowInt(GeneratorInt, GeneratorCompositePow[int]):
    """A Composite Generator that exponentiates two Integer Generators."""


# endregion
# region Composite Classes for And


@dataclass
class GeneratorCompositeAndBool(GeneratorBool, GeneratorCompositeAnd[bool]):
    """A Composite Generator that ands two Boolean Generators."""


# endregion
# region Composite Classes for Or


@dataclass
class GeneratorCompositeOrBool(GeneratorBool, GeneratorCompositeOr[bool]):
    """A Composite Generator that ors two Boolean Generators."""


# endregion
# region Composite Classes for Xor


@dataclass
class GeneratorCompositeXorBool(GeneratorBool, GeneratorCompositeXor[bool]):
    """A Composite Generator that xors two Boolean Generators."""


# endregion

# region Composite Types for Numerics
GeneratorCompositeAddNumeric = Union[
    GeneratorCompositeAddInt, GeneratorCompositeAddFloat
]
GeneratorCompositeSubNumeric = Union[
    GeneratorCompositeSubInt, GeneratorCompositeSubFloat
]
GeneratorCompositeMultNumeric = Union[
    GeneratorCompositeMultInt, GeneratorCompositeMultFloat
]
GeneratorCompositeTrueDivNumeric = GeneratorCompositeTrueDivFloat
GeneratorCompositeFloorDivNumeric = Union[
    GeneratorCompositeFloorDivInt, GeneratorCompositeFloorDivFloat
]
GeneratorCompositePowNumeric = Union[
    GeneratorCompositePowInt, GeneratorCompositePowFloat
]


# endregion

# region Constant Generators


@dataclass
class ConstantStr(GeneratorStr, GeneratorConstant[str]):
    """A Generator that generates a constant string value."""


@dataclass
class ConstantBool(GeneratorBool, GeneratorConstant[bool]):
    """A Generator that generates a constant boolean value."""


@dataclass
class ConstantInt(GeneratorInt, GeneratorConstant[int]):
    """A Generator that generates a constant integer value."""


@dataclass
class ConstantFloat(GeneratorFloat, GeneratorConstant[float]):
    """A Generator that generates a constant float value."""


# endregion
